main: ${project.groupId}.${project.name}
name: ${project.name}
version: ${project.version}
website: ${project.url}
description: ${project.description}
authors: [Cayorion]
depend: [MassiveCore]
load: startup
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  massivelight.basecommand: {description: use the MassiveLight base command, default: false}
  massivelight.fix: {description: fix light in nearby chunks, default: false}
  massivelight.version: {description: see plugin version, default: false}
  massivelight.config: {description: edit config, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  massivelight.*:
    default: false
    children:
      massivelight.basecommand: true
      massivelight.fix: true
      massivelight.version: true
      massivelight.config: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  massivelight.kit.op:
    default: op
    children:
      massivelight.*: true
  massivelight.kit.rank3:
    default: false
    children:
      massivelight.kit.rank2: true
      massivelight.config: true
  massivelight.kit.rank2:
    default: false
    children:
      massivelight.kit.rank1: true
      massivelight.fix: true
  massivelight.kit.rank1:
    default: false
    children:
      massivelight.kit.rank0: true
  massivelight.kit.rank0:
    default: false
    children:
      massivelight.basecommand: true
      massivelight.version: true
  massivelight.kit.default:
    default: true
    children:
      massivelight.kit.rank0: true
